version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  install:
    commands:
      #- apt-get update -y
      # zip is in the image
      #- apt-get install -y zip
      # git-all 
  #pre_build:
    #commands:
      # - command
      # - command
  build:
    commands:
      - ls -lsa
      # the default branch for the project is develop, so no need to switch
      #- git checkout develop
      #- mkdir build
      - cd UI
      - npm run build
      - cd build
      - ls -lsa
      - zip -r bikeshare-node.zip *
      # - command
    #finally:
      #echo Build finished on `date`
  #post_build:
    #commands:
      # - command
      # - command
artifacts:
  files:
    - UI/build/bikeshare-node.zip
    # - location
  #name: $(date +%Y-%m-%d)
  discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths