version: '3.1'

services:

  haproxy:
    image: haproxy:1.9

    ports:
        - 105:80
        - 9999:9999
    volumes:
    # Override volumes
    # Under Docker for Windows, these have to be under the logged in user's User area
        - /C/Users/swood/Documents/Github/js-bikeshare-demo/deploy/Docker:/usr/local/etc/haproxy

    depends_on:
        - bikeshare-ui
        - bikeshare-api

  bikeshare-ui:
    image: bikeshare-ui

    # because we are using a reverse proxy, not need to expose the API port
    #ports:
    #  - 80:80

    env_file: .env

    # if set, these values override settings from env_file
    #environment:
    #  BIKESHARE_API_URL: bikeshare-api

    # Override volumes
    # Under Docker for Windows, these have to be under the logged in user's User area
    # you don't need to do this: the entrypoint.sh will use the nginx.template included 
    # via the docker build
    #volumes:
    #  - /C/Users/swood/Documents/Github/js-bikeshare-demo/UI/docker:/conf

    depends_on:
      - bikeshare-api

  bikeshare-api:
    image: bikeshare-api

    # because we are using a reverse proxy, not need to expose the API port
    #ports:
    #  - 8888:8888

    env_file: .env

