version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  install:
    commands:
      #- apt-get update -y
      # zip is in the image
      #- apt-get install -y zip
      # git-all 
  #pre_build:
    #commands:
      # - command
      # - command
  build:
    commands:
      # make sure we have the latest
      #- git checkout develop: not needed?
      - ls -lsa
      - mkdir nodeBuild
      - cd UI
      - npm install
      - npm run build
      - ls -lsa build
      - zip -r ../nodeBuild/bikeshare-node.zip build/*
      - cd ../deploy/Docker
      - zip ../../nodeBuild/bikeshare-node.zip *
      - cd ../ElasticBeanstalk
      - zip ../../nodeBuild/bikeshare-node.zip *
      - cd ../../nodeBuild
      - zipinfo -1 bikeshare-node.zip
      # - command
    #finally:
      #echo Build finished on `date`
  #post_build:
    #commands:
      # - command
      # - command
artifacts:
  files:
    - nodeBuild/bikeshare-node.zip
    # - location
  #name: $(date +%Y-%m-%d)
  discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths