version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  install:
    commands:
      #- apt-get update -y
      # zip is in the image
      #- apt-get install -y zip
      # git-all 
  #pre_build:
    #commands:
      # - command
      # - command
  build:
    commands:
      # make sure we have the latest
      #- git checkout develop: not needed
      #
      # build React UI app
      - ls -lsa
      - cd UI
      - npm install
      - npm run build
      # build API
      # the Node Beanstalk engine does install
      #- cd ../API
      #- npm install
      #- npm run build
      # create and fill the deployment directory
      - cd ..
      - mkdir target
      - cp -R API/* target
      
      - mkdir target/www
      - cp -R UI/build/* target/www
      
      - mkdir target/.ebextensions
      - cp -R deploy/ElasticBeanstalk/.ebextensions/* target/.ebextensions
      # EBS config in S3. Merged via CodePipeline
      # - command
    #finally:
      #echo Build finished on `date`
  #post_build:
    #commands:
      # - command
      # - command
artifacts:
  files:
    - '**/*'
    #- nodeBuild/bikeshare-node.zip
  base-directory: 'target'
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
#cache:
  #paths:
    # - paths